### ISSUE TITLE
Port of FLAT to the OpenPandora

### ISSUE THREAD

**Issue by ptitSeb** [Cheeseness/FLAT#39]
I have ported FLAT to the OpenPandora (a handheld using an Arm processor running Linux). See here: https://pyra-handheld.com/boards/threads/flat.71093/ for detail and "diff" of the code (mainly adapting graphics to screen res 800x480, and some gameplay adjustement to make it easier).

**Comment by Cheeseness** [comment]
Relevant to this, changes in 33270eadc601f818834222c09adee3ecf3b878b8 remove XRATIO and YRATIO defines, and instead calculate multipliers at runtime based on the resolution that GraphicsManager has been initialised with. Changing DEFAULT_RES_X and DEFAULT_RES_Y in Game.h should be enough to get the game to run at any arbitrary resolution now.

**Comment by Cheeseness** [comment]
I've reworked how enemy spawning works, and added Pandora-specific #defines for a bunch of variables for tuning that. They're currently the same as non-Pandora defaults since I don't have any first hand experiences to tune the game against.

@ptitSeb let me know if/when you get a chance to test with https://github.com/Cheeseness/FLAT/commit/76f127c66a6b609c7b42abc8c39a18cecedf3a67 . Providing it all looks good, I'm happy to mark this issue closed :D

**Comment by ptitSeb** [comment]
I have built it, but I need to fix my old alegro port, I have a segfault at init now.

**Comment by Cheeseness** [comment]
There are new --width and --height arguments in fc3328510e1d641d717ef708e4608c95851afd74 that might be helpful/relevant if testing the same binaries on the Pandora and Prya is desired.

**Comment by ptitSeb** [comment]
Yes, that will be usefull. The control would be similar on the Pyra than on the Pandora. Build should be easier also (hopefully), as I probably wont need my custom build of Allegro there.
I still haven't fixed my Allegro issue on the Pandora. It seems to create a context and close it and than gather the available GLES extension. Need to understand why the context is closed after beeing correctly initialized.

**Comment by Cheeseness** [comment]
Oh darn. Does it die in the Allegro example apps as well or just FLAT?

**Comment by ptitSeb** [comment]
Examples works yes. I haven't re-tried the demo games.

**Comment by Cheeseness** [comment]
Hmm, are you at the repo head? I found that Game's destructor was being called at startup before the actual instance was instantiated, and resolved that in 9e2f139f00fbd0ec0703fdaab817670a19f096c7 - if you're on an older commit, is it possible that that's relevant?

**Comment by ptitSeb** [comment]
I'm detached at 76f127c
Maybe I should just go the master/HEAD?

**Comment by Cheeseness** [comment]
Hmm, that's after that change in Game instantiation. Doesn't hurt to sync up, but I don't think there've been any changes since that are likely to be relevant.

**Comment by Cheeseness** [comment]
I guess another idea would be to try to build against the original port and see if it has the same problem. The commit at that point was f8335eb9cac7d191efb5965b7c9b7b0b113bee57, and I was able to the orginal patch in [this thread](https://pyra-handheld.com/boards/threads/flat.71093/) (I updated the issue description with the new URL).

Not wanting to put any pressure on, but I'm keen to help/be supportive in any way I can!

**Comment by ptitSeb** [comment]
So, I found the issue.
It's because my Allegro port use GLESv2 now, but FLAT links with GLES_CM on Pandora config. and it make a conflict. I remove the GLES_CM and it launched!

It was working smoothly now.
But I skate and grabbed the gun. After that, nothing really happened. I could continue skatting, and shooting, but no enemy poped, no where.
Also, I'm unsure how to quit, I have to check that. I can pause, but not quit.

**Comment by Cheeseness** [comment]
Ah, fantastic! Glad to hear you're up and running :)

At the moment, you'll need to hold down the forward key while skating to go fast enough for enemies to spawn. Historically, we left it that way so that enemies would be less likely to spawn while you were in combat, since you'll generally be moving slower.

There is no quit button - as I mentioned earlier, I'd like to implement at least a rudimentary menu so that you can pause and then quit. If you think that a dedicated quit button is a better fit for the platform, I can definitely add that back in.

**Comment by ptitSeb** [comment]
Menu is fine. Not need for a dedicated button.

Yes, getting some speed and the enemy poped. No speed issue, but I did loose pretty quickly.

**Comment by Cheeseness** [comment]
So, depending on how far I get with menu stuff, I'm open to the idea of adding difficulty settings so that things like max enemy number, enemy health, and player health can be adjusted by the player. If there are performance concerns, then I think it makes sense to have separate values for the OpenPandora, but if not, I feel like it's probably best to leave difficulty consistent between platforms.

In case you didn't spot my edit to my last post, would you be willing to share a photo of the game running on an OpenPandora that I could include in a post about the game's history?

**Comment by ptitSeb** [comment]
Like that?
![image](https://user-images.githubusercontent.com/3250792/140607189-a8e78fe5-a762-4568-a379-1b8bc6d15078.png)

**Comment by Cheeseness** [comment]
That's fantastic, thank you! :D

**Comment by Cheeseness** [comment]
I've just pushed up a first pass for a menu implementation. It currently doesn't have proper layout and doesn't care about resolution, but it's functional and allows the game to be quit from the main menu, end screen, and death screen (to quit a game in progress, pause and then return to the main menu). It also allows a new game to be started without quitting the game.

I'll polish it up over the next day or two, and then I think we can call this issue closed!

**Comment by Cheeseness** [comment]
OK, menus are now scaling enough that they should be functional!

In the original Pandora port, it was calculating an independent multiplier for width and height, which was resulting in the game being squished a little (the moons weren't quite circular, and when the camera tilts, the mountains were visibly leaving the ground). I fixed it to use whichever is larger for both - assuming that the Pandora has square pixels, that should look better :)

@ptitSeb, assuming you have time to confirm that the UI is usable, I'm feeling like we're at a good point to close this issue :D

Known issues that I plan to address, but probably don't need to be blockers:
* the unchecked state for checkbox/toggle buttons in the settings menu are hard to read
* main menu and how to play screens don't look good where text overlaps images
* settings menu keyboard navigation can be awkward

**Comment by Cheeseness** [comment]
Actually, make that 5800dae4c11b162136e6f325ff0980c46df1112f

**Comment by ptitSeb** [comment]
Ok, I'll update the build and test it on a pandora

**Comment by ptitSeb** [comment]
Mmm, I have an issue on the Menu: it does 2 jumps, Up or Down, each time I press the keypad.

**Comment by ptitSeb** [comment]
But the menu does fit the screen nicely

**Comment by Cheeseness** [comment]
Just pushed up a fix (KEY_UI_UP and KEY_UI_DOWN were also bound the same buttons as KEY_FORWARD and KEY_BACKWARD). Give current head (5eebb0dc122f382b835c9ab0cfcccca4b247f170) a try!

**Comment by ptitSeb** [comment]
Ok, yes, menu works fine now :)

I tried starting a new game, and I got
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
FLAT.arm: xcb_io.c:256: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
Not sure if it's my Allegro port behaving incorrectly...

**Comment by Cheeseness** [comment]
Hmm, I haven't done anything threading-related. Can you switch to other menu screens without it crashing, or only when you start a new game?

You said that gameplay was working before in [this comment](https://github.com/Cheeseness/FLAT/issues/39#issuecomment-962417952) before I added the menu system - was that with the same Allegro build you're using now?

**Comment by ptitSeb** [comment]
Yes, all menu works, only starting the game crashes (even if I select no sub-menu).

Yes, same Allegro build that was working with the version without the menu.

**Comment by Cheeseness** [comment]
Strange! I'll have more of a look into it later tonight.

Is it easy to attach a debugger to the process? It might be helpful to know how far it's getting through newGame()

**Comment by ptitSeb** [comment]
So, I fixed it on my side. I added the "XInitThreads()" function call when initializing the Pandora port of allegro. I guess it wass working before by luck.
It works nicely on my pandora. I'll package it tonight and will publish the updated version on the Pandora software repo. I'll check to make a Pyra version later.

**Comment by Cheeseness** [comment]
Great! I've got a few more changes I want to do before the new Itch version goes up for PC platforms, but I'm aiming to have those ready for the weekend if you'd rather wait for those.

In the meantime, I'm happy to consider the ported merged now, and work from this point forward can be development and maintenance. Are you happy for me to close this issue and we can open individual issues for any future stuff that arises?

I'm excited to hear how it looks/runs on the Pyra!

**Comment by ptitSeb** [comment]
Sure, I can wait for this WeekEnd of course!

And yes, this ticket can be closed. Port is working fine.

I'll probably try it on Pyra this weekend...

**Comment by Cheeseness** [comment]
Fantastic. Thank you so much again for your effort, and sorry for taking so long to get it merged. I'm very happy to have your contribution officially "in" :)

**Comment by Cheeseness** [comment]
New PC builds are up and released now. Feel free to go ahead with new Pandora builds ( you might want to take a look at #43 first, though ) :D

**Comment by ptitSeb** [comment]
I'll package the new version. I haven't seen on the menu where the key name are used.
Anyway, my dev pandora is dying :( The "classic" issue with the LCD ribbon (the decise of all clam-shell device), so my screen is starting to show large pink zone.
Still usable, but very anoying. I also have 2 other pandora, but those are less powerfull models, so I'll porbably slow down a lot Pandora dev.

But I'll build a pyra version soon.

**Comment by Cheeseness** [comment]
This is the screen. You can get there from the main menu
![how-to-play_menu](https://user-images.githubusercontent.com/1570520/141612945-15aad6b7-6e4f-4d2b-8086-ba1dc009d9b6.png)

Oh, something I forgot to mention - the version displayed on the settings screen is set by a preprocessor define. If you invoke cmake at configure time like this, it'll use the current git tag and commit number, which is how I'm storing the version in PC builds.
`$ cmake .. -DVERSION_NUMBER="$(git describe --abbrev=8 --dirty --always --tags --long)"`
